### PR TITLE
Swiftify code

### PR DESCRIPTION
**Pull request by dehesa**
Hi,

First of all, thanks for writing this little tool. Very useful! 👍 
While playing with it, I swiftify it a bit. Here is an enumeration of the changes:
- Add a .gitignore.
- Change Xcode settings to Xcode 8 and support macOS to 10.12
- Swiftify IOKeyboardEventManager and rename it to LayoutManager.
   Swiftify means things like using `guard` statements, make the `class` `final`, make member variables private or constants, divide code using extensions, etc.

If you have information on good I/O Kit examples for using/modifying the keyboard events from Swift, I will be happy to hear it :)

Regards,
Marcos

### CODE REVIEW

**Comment by jeantil** [comment]
Hi, 
Thanks for taking the time to write this PR and sorry it took so long for me to notice.

>Add a .gitignore
I am not convinced by the provided gitignore. I don't see any project specific ignores which tends to indicate that these should be added to your ~/.gitignore instead of to the project. 
I mostly do scala development and I have no idea what are standard practices in the xcode world are :) Is it normal to copy paste the same basic .gitignore in each project ? 

>Change Xcode settings to Xcode 8 and support macOS to 10.12
Same as my previous question, I am wholly unfamiliar with the general OSX ecosystem. 
What does it bring to the project to upgrade and not be backward compatible anymore ? This is a genuine question, I have no idea what upgrading will imply. I am not opposed but some reason for the change would be nice :) 
Also it seems that doing the change you removed my "team" from the project. As far a I know that"s the only way for me to sign the binaries. As I understand it, running unsigned binaries requires specific setup on the host.

>Swiftify IOKeyboardEventManager and rename it to LayoutManager.
> Swiftify means things like using guard statements, make the class final, make member variables private or constants, divide code using extensions, etc.

I am very interested in this. 
I do agree with the name change but please avoid renaming and changing the code in the same commit. It makes it very hard for me to understand what changed.

**Comment by dehesa** [comment]
Hi @jeantil. Sorry for my late answer. I intended to write to you and then I forgot 😄 Let me try to write my wrong now as best as I can.

> Add a .gitignore

Adding a `.gitignore` is one of the first things I do (and many developers also do) when starting a project that is intended to be shared. It will filter out some temporal or user-specific files that your computer generate. The `.gitignore` file I added is a standard on macOS development. Among other things, it will filter out:
- macOS temporal files, such as the [`.DS_Store`](https://en.wikipedia.org/wiki/.DS_Store), which is a cache file generated by Finder in your mac while navigating the file structure.
- Xcode temporal and user-specific files. These are files that only pertain to you. For example, if you right click on `autokbisw.xcodeproj`, select "Show Package Contents", and then navigate to `xcuserdata`, I can see the folder `jean.xcuserdatad` with your preferences on Xcode UI, some debugging points, etc. When you are collaborating with people on a project, this list will start to grow and it is completely useless to me or any other collaborator.
- Package Managers build folders. In case someone will like to use your project with SwiftPM, Carthage, etc. Although you don't do this know, it is good practice to already filter it out, since someone can start using your project without the intention of collaborating. After some time of using it on their pipeline, they may decide to send back their changes and it will get annoying if the have to manually filter in git their pipeline marks.
I always add a `.gitignore` on my first commit :)

> Change Xcode settings to Xcode 8 and support to 10.12

This has two answers:
- Change of project file to support Xcode 8 format. You do this by selecting your project file in the Xcode navigator and then select View > Utilities > Show File Inspector (or pressing ⌥+⌘+1); then in the "Project Document" section select "Project Format".
  This only specifies the way that the project file is internally expressed (you can check it out by using Finder, right clicking on `autokbisw.xcodeproj` > "Show Package Contents" and then just looking in an editor the `project.pbxproj` file). All projects are defined in some xmlish Apple Private format way. By selecting Xcode 8 format, you are saying that you want to have the most updated file format. Since you are doing the project in Swift 3 and swift can only be comfortably programmed with Xcode 8, it is better to select this.
- Support for macOs 10.12. The internal macOS frameworks tend to change quite a bit with every macOS iteration. These changes are not very "visible" since not many people are working with them.  For example to creator of [Karabiner](https://pqrs.org/osx/karabiner/index.html.en) had to change the way he was exposing his HID layouts since it completely changed in macOS 10.12.
  When you say you are supporting just the latest version, you will get warning on deprecated APIs, etc and you may see modified behavior when interacting with certain objects. Since this is a personal project and you are not providing binaries (for now). I deem best to develop on the latest version and keep up with the changes.

> The Swift questions :)

If you have any questions, I can go one by one. But I am not sure which ones you want me to answer. I do agree with you that naming the file was a poor choice, since then you cannot see the changes.

> Addendum

I can add some pull requests with the changes that you accept and I will add some more PRs about Swift syntax (such as not using semicolons at the end of statements, not using MutableDictionaries if not needed, etc.).

**Comment by jeantil** [comment]
Hello, 

Regarding the Xcode8 format and support for MacOS10.12, I'll make these changes and make sure my API usage is correct. Thanks a lot for pointing this out in a detailed way this is really useful to know.

A quick note: 
> Since this is a personal project and you are not providing binaries (for now).

Actually I am though it is not publicized in the readme :) 
Signed binaries are available in the "release" section of the repository (if only because it's a convenient place to have co-workers download them from when I pair on their laptop :) )

>macOS temporal files, such as the .DS_Store, which is a cache file generated by Finder in your mac while navigating the file structure.

Regarding the .gitignore file 
* >macOS temporal files, such as the .DS_Store, which is a cache file generated by Finder in your mac while navigating the file structure.
Adding system-specific files to the repo's .gitignore is considered a poor practice. These should definitely be excluded system wide through the use of the global gitignore. 
You will find numerous articles about having a global gitignore for these things. You can also check the github [help page on gitignore](https://help.github.com/articles/ignoring-files/#create-a-global-gitignore) and the associated [blog post](http://augustl.com/blog/2009/global_gitignores) or [my favorite one](https://thomashunter.name/blog/global-gitignore-vs-repository-gitignore/)
* >Package Managers build folders.
This one is less clear cut. I'll trust you that the OSx dev community usually includes them and add the corresponding .gitignore entries to the project. 
* >Xcode temporal and user-specific files.
I rechecked the rules and I can't add them as they are since they would break cli build. 
The content of autokbisw.xcodeproj is as follows :
```
$ tree autokbisw.xcodeproj
autokbisw.xcodeproj
├── project.pbxproj
├── project.xcworkspace
│   ├── contents.xcworkspacedata
│   └── xcuserdata
│       └── jean.xcuserdatad
│           └── UserInterfaceState.xcuserstate
└── xcuserdata
    └── jean.xcuserdatad
        ├── xcdebugger
        │   └── Breakpoints_v2.xcbkptlist
        └── xcschemes
            ├── autokbis.xcscheme
            └── xcschememanagement.plist
```

the autokbis.xcsheme is defined in the may xcuserdata directory so ignoring all of xcuserdata would be problematic. 

I'll add selective ignore rules for 
* autokbisw.xcodeproj/project.xcworkspace/xcuserdata 
* autokbisw.xcodeproj/xcuserdata/xcdebugger

Removing the whole thing would make it impossible to share the xcsheme which seems necessary to build the app (for instance from a CI server)

How is that issue usually solved in your experience ?  

> I can add some pull requests with the changes that you accept and

I used your PR to refactor the code on my own using atomic commits for each changes (see the list of commits in #5) A review of these to make sure I haven't forgotten anything would be much appreciated. The only change I made a conscious decision not to pick from your PR is the use of guard in `restoreInputSource`. I read up on guard, what it is intended to be used for and I feel it doesn't apply properly there. 

If you see some things to improve your changes are very welcome, but please make atomic commits for each change so I can learn and review faster :)

**Comment by dehesa** [comment]
Great review, thanks @jeantil 

About the `.xcscheme`s files, remember that you can (and should) make the schemes that you use on the CI (or any one you want for other developers) shared by clicking on your current Scheme > "Manage Schemes" and then clicking on the "Shared" button for the schemes you want.

**Pull request closed without merging**
