### PR TITLE
Build with SwiftPM and avoid code signing 

### PR DESCRIPTION
**Pull request by ratkins**
Rebuilt PR from yesterday incorporating your suggestions, hopefully the history comes out nicer this time. The Homebrew formula isn't in here as it belongs solely in the Homebrew repo. I'll add that once you publish a new release including this PR.

### CODE REVIEW

**Comment by jeantil** [comment]
I have reviewed and merged your changes. 
Thanks for splitting the commits. the history for main is split but it's a small enough file that it doesn't matter. 
I'll try to make a release tonight when I get home.

**Comment by ratkins** [comment]
Yeah, sorry about `main.swift`, I couldn't convince git it was the same file for no lack of trying. Thanks for merging! After you create the release I'll submit the homebrew formula.

**Comment by jeantil** [comment]
I have restored the plist file as it is useful for those who do not use homebrew. In the homebrew PR, I would really appreciate if you add the relevant comments from the sample plist. 
They demonstrate : 
- the available cli options
- the way to activate debug logs 

this is very useful to me when people report issues here as I can tell to look at the plist file to see how to enable both :)
It took me way too long to find the relevant information when I had to look for it so adding the relevant bits in the sample is very useful.

**Comment by jeantil** [comment]
I have release 1.2.0 based on your PR.

**Pull request merged**
